import { StyleSheet, Platform } from 'react-native';
import { Spacing, MaxContentWidth } from '@/constants/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  content: {
    paddingHorizontal: Spacing.four,
    gap: Spacing.three,
    maxWidth: MaxContentWidth,
    alignSelf: 'center',
    width: '100%',
    paddingTop: Spacing.three,
    paddingBottom: Spacing.six,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: Spacing.two,
  },
  laurelLogoBtn: {
    padding: 2,
  },
  laurelRing: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: '#FF9100',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 145, 0, 0.15)',
    boxShadow: '0 0 12px rgba(255, 145, 0, 0.40)',
  },
  laurelLetter: {
    fontSize: 20,
    fontWeight: '900',
    color: '#FFAB00',
  },
  headerContainerMaster: {
    alignItems: 'center',
    width: '100%',
    marginBottom: 10,
    gap: 6,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  titleCenterMaster: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandSubtitleBadge: {
    backgroundColor: 'rgba(212, 175, 55, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.45)',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 3,
  },
  brandSubtitle: {
    fontSize: 10,
    fontFamily: 'monospace',
    fontWeight: '900',
    color: '#FFE259',
    letterSpacing: 2,
    textAlign: 'center',
  },
  actionDockPill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    backgroundColor: 'rgba(13, 17, 28, 0.85)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 5,
    marginTop: 2,
  },
  actionDockBtn: {
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  headerRightActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(13, 17, 28, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
  },
  dateRowCenter: {
    alignItems: 'center',
    marginVertical: 2,
  },
  dateHeaderText: {
    fontSize: 11,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    color: '#94A3B8',
    letterSpacing: 1.5,
  },
  heroGaugeSection: {
    alignItems: 'center',
    marginVertical: 4,
  },
  sectionHeaderTitle: {
    fontSize: 11,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    color: '#C5A869',
    letterSpacing: 3,
    marginBottom: 4,
  },
  cardHeaderGoldText: {
    fontSize: 10,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    color: '#C5A869',
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  pactStatusCard: {
    backgroundColor: 'rgba(14, 20, 36, 0.92)',
    borderRadius: 16,
    padding: Spacing.four,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.38)',
    gap: 12,
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  pactHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pactTitleCol: {
    gap: 2,
  },
  dayBadgeRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
  },
  pactDayNumber: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
    fontFamily: 'monospace',
  },
  pactDayTotal: {
    fontSize: 13,
    color: '#94A3B8',
    fontFamily: 'monospace',
  },
  gradeBadgeContainer: {
    borderRadius: 14,
    overflow: 'hidden',
  },
  gradeBadgeGradient: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gradeBadgeText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#FFFFFF',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  pillarsGridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
  },
  pillarPill: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 4,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.2)',
    gap: 2,
  },
  pillarPillActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderColor: 'rgba(16, 185, 129, 0.45)',
  },
  pillarIconText: {
    fontSize: 13,
    fontWeight: 'bold',
  },
  pillarLabel: {
    fontSize: 10,
    color: '#94A3B8',
    fontWeight: '600',
    fontFamily: 'monospace',
  },
  pillarLabelActive: {
    color: '#6EE7B7',
    fontWeight: 'bold',
  },
  pactFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: 'rgba(212, 175, 55, 0.15)',
  },
  pactStatusText: {
    fontSize: 11,
    color: '#CBD5E1',
    flex: 1,
    marginRight: 8,
  },
  viewJudgmentBtn: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.5)',
  },
  viewJudgmentBtnText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#FDE68A',
    fontFamily: 'monospace',
  },
  twoColRow: {
    flexDirection: 'row',
    gap: Spacing.three,
  },
  halfCard: {
    flex: 1,
    backgroundColor: 'rgba(13, 17, 28, 0.92)',
    borderRadius: 16,
    padding: Spacing.three,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    justifyContent: 'space-between',
    gap: 8,
  },
  workoutGoldBox: {
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.40)',
    gap: 2,
  },
  workoutTitleText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#FDE68A',
  },
  workoutMetaText: {
    fontSize: 11,
    color: '#D4AF37',
    fontFamily: 'monospace',
  },
  startButtonTouch: {
    marginTop: 4,
  },
  startButtonGradient: {
    paddingVertical: 9,
    paddingHorizontal: 8,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 4,
  },
  startButtonText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#050507',
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  stoicQuoteText: {
    fontSize: 12,
    fontFamily: 'serif',
    fontStyle: 'italic',
    color: '#E2E8F0',
    lineHeight: 17,
    flexShrink: 1,
  },
  stoicAuthorText: {
    fontSize: 10,
    fontFamily: 'monospace',
    color: '#C5A869',
    alignSelf: 'flex-end',
    marginTop: 4,
    flexShrink: 1,
  },
  healthMetricsCard: {
    backgroundColor: 'rgba(14, 20, 36, 0.88)',
    borderRadius: 16,
    padding: Spacing.three,
    borderWidth: 1,
    borderColor: 'rgba(226, 192, 104, 0.35)',
    gap: 8,
    overflow: 'hidden',
  },
  metricsGridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 4,
  },
  metricCol: {
    flex: 1,
    minWidth: 65,
    alignItems: 'center',
    gap: 2,
  },
  metricLabelText: {
    fontSize: 9.5,
    color: '#94A3B8',
    fontFamily: 'monospace',
    textAlign: 'center',
  },
  metricValText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'monospace',
  },
  unitText: {
    fontSize: 10,
    color: '#94A3B8',
    fontWeight: 'normal',
  },
  metricDividerLine: {
    width: 1,
    height: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.10)',
  },
  extraModulesContainer: {
    marginTop: Spacing.two,
    gap: Spacing.three,
  },
  quickDockCard: {
    backgroundColor: 'rgba(14, 20, 36, 0.90)',
    borderRadius: 16,
    padding: Spacing.three,
    borderWidth: 1,
    borderColor: 'rgba(29, 100, 242, 0.30)',
    gap: 8,
    marginVertical: 4,
  },
  dockHeaderTitle: {
    fontSize: 10,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    color: '#00C6FF',
    letterSpacing: 1.5,
    textAlign: 'center',
  },
  dockButtonsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  dockChipBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  dockChipActive: {
    backgroundColor: 'rgba(226, 192, 104, 0.20)',
    borderColor: '#E2C068',
  },
  dockChipText: {
    fontSize: 11.5,
    fontWeight: '600',
    color: '#F8FAFC',
    fontFamily: 'monospace',
  },
  dockChipTextActive: {
    color: '#E2C068',
    fontWeight: 'bold',
  },
  pillarSectionGroup: {
    gap: Spacing.three,
    marginTop: Spacing.two,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
  },
  sectionPillarTitle: {
    fontSize: 11,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    color: '#E2C068',
    letterSpacing: 1.8,
  },
  sectionPctBadge: {
    fontSize: 11,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    color: '#00C6FF',
    backgroundColor: 'rgba(0, 198, 255, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 198, 255, 0.30)',
  },
  sectionPctBadgeGold: {
    fontSize: 11,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    color: '#E2C068',
    backgroundColor: 'rgba(226, 192, 104, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(226, 192, 104, 0.30)',
  },
  boxBreathingTriggerBtn: {
    marginTop: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(56, 189, 248, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  boxBreathingTriggerText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#7DD3FC',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
});

