import { StyleSheet, Platform } from 'react-native';
import { Spacing, MaxContentWidth } from '@/constants/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  content: {
    paddingHorizontal: Spacing.four,
    paddingTop: Spacing.three,
    paddingBottom: Spacing.six,
    gap: Spacing.three,
    maxWidth: 600,
    alignSelf: 'center',
    width: '100%',
  },
  header: {
    marginBottom: 4,
  },
  label: {
    fontSize: 10,
    fontFamily: 'monospace',
    letterSpacing: 2,
    color: '#10B981',
    fontWeight: 'bold',
  },
  title: {
    fontSize: 24,
    fontFamily: 'serif',
    fontWeight: 'bold',
    marginTop: 2,
  },
  card: {
    borderRadius: 16,
    padding: Spacing.three,
    borderWidth: 1,
    gap: Spacing.two,
  },
  badgeContainer: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  lastScoreRow: {
    marginTop: 6,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
  },
  densityPill: {
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  actionGrid: {
    gap: 12,
  },
  actionBtnTouch: {
    borderRadius: 14,
    overflow: 'hidden',
  },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 14,
    borderRadius: 14,
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 4,
  },
  actionBtnText: {
    color: '#050507',
    fontWeight: '900',
    fontSize: 14,
    fontFamily: 'monospace',
    letterSpacing: 1,
  },
  actionBtnSecondary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1.2,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    backgroundColor: 'rgba(212, 175, 55, 0.08)',
  },
  actionBtnSecondaryText: {
    fontWeight: 'bold',
    fontSize: 14,
    fontFamily: 'monospace',
    color: '#FDE68A',
  },
  manualBtn: {
    alignItems: 'center',
    paddingVertical: 4,
  },
  loadingBox: {
    padding: Spacing.four,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(13, 17, 28, 0.96)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.45)',
  },
  resultCard: {
    borderRadius: 18,
    padding: Spacing.four,
    borderWidth: 1.5,
    gap: 10,
  },
  scannedImageContainer: {
    position: 'relative',
    borderRadius: 14,
    overflow: 'hidden',
  },
  scannedImage: {
    width: '100%',
    height: 190,
    borderRadius: 14,
  },
  confidenceOverlayBadge: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    backgroundColor: 'rgba(5, 5, 8, 0.85)',
    borderWidth: 1,
    borderColor: '#10B981',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  confidenceOverlayText: {
    fontSize: 9.5,
    color: '#A7F3D0',
    fontWeight: '900',
    fontFamily: 'monospace',
  },
  dishHeaderBox: {
    backgroundColor: 'rgba(212, 175, 55, 0.08)',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    gap: 4,
  },
  dishHeaderLabel: {
    fontSize: 9.5,
    color: '#D4AF37',
    fontFamily: 'monospace',
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  dishNameInput: {
    fontSize: 17,
    fontFamily: 'serif',
    fontWeight: 'bold',
    color: '#FFE259',
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(212, 175, 55, 0.3)',
  },
  dishMetaRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
  },
  metaPill: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  metaPillText: {
    fontSize: 10,
    color: '#CBD5E1',
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  ingredientsSection: {
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    gap: 8,
  },
  ingredientsSectionTitle: {
    fontSize: 10,
    color: '#38BDF8',
    fontFamily: 'monospace',
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  ingredientRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
    paddingBottom: 6,
  },
  ingredientName: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  ingredientGrams: {
    fontSize: 9.5,
    color: '#94A3B8',
    fontFamily: 'monospace',
  },
  ingredientMacrosBox: {
    alignItems: 'flex-end',
  },
  ingredientCals: {
    fontSize: 11.5,
    fontWeight: '900',
    color: '#FFE259',
    fontFamily: 'monospace',
  },
  ingredientMacros: {
    fontSize: 8.5,
    color: '#94A3B8',
    fontFamily: 'monospace',
  },
  visualCuesBox: {
    gap: 4,
  },
  visualCuesTitle: {
    fontSize: 9.5,
    fontFamily: 'monospace',
    color: '#94A3B8',
    fontWeight: 'bold',
  },
  visualCuesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  visualCueChip: {
    backgroundColor: 'rgba(212, 175, 55, 0.10)',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.25)',
  },
  visualCueText: {
    fontSize: 9.5,
    color: '#FDE68A',
  },
  stoicQuote: {
    fontSize: 11.5,
    fontStyle: 'italic',
    color: '#CBD5E1',
    lineHeight: 16,
    textAlign: 'center',
    marginVertical: 2,
  },
  calibrationHeader: {
    fontSize: 10,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    color: '#D4AF37',
    letterSpacing: 1,
    marginTop: 4,
  },
  editableBreakdownGrid: {
    flexDirection: 'row',
    gap: 6,
  },
  editableField: {
    flex: 1,
    backgroundColor: 'rgba(13, 17, 28, 0.95)',
    borderRadius: 10,
    padding: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
  },
  fieldLabel: {
    fontSize: 8.5,
    color: '#94A3B8',
    fontFamily: 'monospace',
    marginBottom: 2,
  },
  fieldInput: {
    fontSize: 15,
    fontWeight: '900',
    color: '#FFFFFF',
    fontFamily: 'monospace',
    textAlign: 'center',
    width: '100%',
    paddingVertical: 2,
  },
  stepperRow: {
    flexDirection: 'row',
    gap: 4,
    marginTop: 4,
  },
  stepperBtn: {
    backgroundColor: 'rgba(212, 175, 55, 0.2)',
    borderRadius: 4,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  stepperText: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#FFE259',
    fontFamily: 'monospace',
  },
  microNutrientsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(212, 175, 55, 0.08)',
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.20)',
  },
  microTxt: {
    fontSize: 11,
    color: '#FDE68A',
    fontFamily: 'monospace',
  },
  verdictBox: {
    backgroundColor: 'rgba(212, 175, 55, 0.10)',
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.30)',
  },
  scienceToggleBtn: {
    alignItems: 'center',
    paddingVertical: 4,
  },
  scienceToggleText: {
    fontSize: 10.5,
    color: '#38BDF8',
    fontFamily: 'monospace',
    textDecorationLine: 'underline',
  },
  scienceExplainerBox: {
    backgroundColor: 'rgba(15, 23, 42, 0.90)',
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.3)',
  },
  scienceExplainerText: {
    fontSize: 10,
    color: '#94A3B8',
    lineHeight: 15,
  },
  confirmBtnTouch: {
    marginTop: 4,
    borderRadius: 12,
    overflow: 'hidden',
  },
  confirmBtn: {
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmBtnText: {
    color: '#050507',
    fontWeight: '900',
    fontFamily: 'monospace',
    fontSize: 12,
    letterSpacing: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(5, 5, 7, 0.90)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.three,
  },
  modalCard: {
    width: '100%',
    maxWidth: 380,
    borderRadius: 16,
    padding: Spacing.four,
    gap: Spacing.two,
    borderWidth: 1.5,
    borderColor: 'rgba(212, 175, 55, 0.45)',
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: 'serif',
    fontWeight: 'bold',
    marginBottom: 4,
  },
  inputGroup: {
    gap: 4,
  },
  inputLabel: {
    fontSize: 11,
    fontFamily: 'monospace',
    color: '#94A3B8',
  },
  textInput: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    fontSize: 16,
    fontFamily: 'monospace',
  },
  modalButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: Spacing.two,
    marginTop: 8,
  },
  cancelBtn: {
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  saveBtn: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
});
