import { StyleSheet, Platform } from 'react-native';
import { Spacing, MaxContentWidth } from '@/constants/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    paddingHorizontal: Spacing.four,
    maxWidth: MaxContentWidth,
    alignSelf: 'center',
    width: '100%',
  },
  content: {
    paddingBottom: Spacing.six,
  },
  header: {
    marginTop: Spacing.two,
    marginBottom: Spacing.three,
  },
  backBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(212, 175, 55, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
  },
  backBtnText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#FFE259',
    fontFamily: 'monospace',
  },
  label: {
    fontSize: 10,
    textTransform: 'uppercase',
    color: '#D4AF37',
    letterSpacing: 3,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  title: {
    fontSize: 26,
    fontFamily: 'serif',
    marginTop: 4,
    textTransform: 'uppercase',
    fontWeight: '900',
    color: '#FFE259',
  },
  avatarHeroCard: {
    alignItems: 'center',
    paddingVertical: Spacing.four,
    backgroundColor: 'rgba(13, 17, 28, 0.94)',
    borderWidth: 1.5,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    borderRadius: 16,
    marginBottom: Spacing.three,
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
  },
  avatarContainer: {
    position: 'relative',
    marginBottom: Spacing.two,
  },
  avatarImage: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 2,
    borderColor: '#D4AF37',
  },
  avatarPlaceholder: {
    width: 90,
    height: 90,
    borderRadius: 45,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#D4AF37',
  },
  cameraBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#050507',
  },
  userNameText: {
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'serif',
    marginTop: 4,
    color: '#FFFFFF',
  },
  userRoleText: {
    fontSize: 11,
    color: '#D4AF37',
    fontFamily: 'monospace',
    marginTop: 2,
  },
  presetRow: {
    marginTop: Spacing.three,
    alignItems: 'center',
  },
  presetLabel: {
    fontSize: 10,
    fontFamily: 'monospace',
    color: '#94A3B8',
  },
  presetChip: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    backgroundColor: 'rgba(212, 175, 55, 0.10)',
    borderRadius: 6,
  },
  presetChipText: {
    fontSize: 10,
    fontFamily: 'monospace',
  },
  description: {
    fontSize: 13,
    fontStyle: 'italic',
    lineHeight: 20,
    marginBottom: Spacing.four,
    color: '#CBD5E1',
    textAlign: 'center',
  },
  section: {
    borderWidth: 1.5,
    borderRadius: 14,
    padding: Spacing.four,
    marginBottom: Spacing.four,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    backgroundColor: 'rgba(13, 17, 28, 0.94)',
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 2,
    color: '#D4AF37',
    marginBottom: Spacing.three,
    fontFamily: 'monospace',
  },
  calibrateButton: {
    marginTop: 12,
    backgroundColor: '#D4AF37',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: Spacing.two,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(212, 175, 55, 0.15)',
  },
  rowLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#F8FAFC',
  },
  rowValue: {
    fontSize: 14,
    color: '#CBD5E1',
    fontFamily: 'monospace',
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: Spacing.three,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(212, 175, 55, 0.15)',
  },
  hint: {
    fontSize: 11,
    color: '#94A3B8',
    marginTop: 2,
  },
  dangerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.three,
    gap: Spacing.two,
  },
  dangerText: {
    color: '#FF453A',
    fontWeight: 'bold',
    fontSize: 14,
    fontFamily: 'monospace',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: Spacing.two,
    paddingHorizontal: Spacing.three,
    backgroundColor: 'rgba(212, 175, 55, 0.10)',
    borderRadius: 6,
    marginBottom: Spacing.three,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.25)',
  },
  statusText: {
    fontSize: 10,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  uidButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 2,
    paddingHorizontal: 8,
    backgroundColor: 'rgba(212, 175, 55, 0.12)',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
  },
  uidText: {
    fontSize: 12,
    fontFamily: 'monospace',
    color: '#FFE259',
    letterSpacing: 1,
  },
  warningBox: {
    flexDirection: 'row',
    gap: 8,
    marginTop: Spacing.three,
    padding: Spacing.three,
    backgroundColor: 'rgba(245, 158, 11, 0.08)',
    borderLeftWidth: 2,
    borderLeftColor: '#F59E0B',
    borderRadius: 4,
  },
  warningText: {
    flex: 1,
    fontSize: 11,
    color: '#FDE68A',
    lineHeight: 17,
    fontFamily: 'monospace',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(5, 5, 7, 0.90)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.four,
  },
  modalContent: {
    width: '100%',
    maxWidth: 420,
    padding: Spacing.four,
    borderWidth: 1.5,
    borderRadius: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.four,
  },
  modalTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  inputLabel: {
    fontSize: 10,
    fontFamily: 'monospace',
    marginBottom: 4,
    color: '#D4AF37',
  },
  input: {
    borderWidth: 1,
    padding: Spacing.two,
    fontFamily: 'monospace',
    fontSize: 14,
    borderRadius: 8,
  },
  saveBtn: {
    paddingVertical: Spacing.three,
    alignItems: 'center',
  },
  archetypeOptionCard: {
    backgroundColor: 'rgba(13, 17, 28, 0.85)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.22)',
    borderRadius: 12,
    padding: Spacing.three,
  },
  archetypeOptionCardSelected: {
    borderColor: '#D4AF37',
    backgroundColor: 'rgba(212, 175, 55, 0.12)',
    borderWidth: 1.5,
  },
  archetypeOptionIconRing: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  archetypeOptionName: {
    fontSize: 13,
    fontWeight: '900',
    color: '#FFF',
  },
  selectedPillBadge: {
    backgroundColor: '#D4AF37',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  selectedPillText: {
    fontSize: 8,
    fontWeight: '900',
    color: '#050507',
    fontFamily: 'monospace',
  },
  archetypeOptionTagline: {
    fontSize: 10.5,
    color: '#CBD5E1',
    marginTop: 2,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  actionRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  changeLinkText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#FFE259',
    letterSpacing: 1.2,
    fontFamily: 'monospace',
  },
  condecorationCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#FFE259',
    gap: 12,
    marginBottom: Spacing.four,
    shadowColor: '#FFE259',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
  },
  condecorationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
    paddingBottom: 10,
  },
  condecorationTag: {
    fontSize: 9,
    fontFamily: 'monospace',
    color: '#D4AF37',
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  condecorationRankTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#FFE259',
    fontFamily: 'serif',
  },
  condecorationBadge: {
    backgroundColor: 'rgba(212, 175, 55, 0.18)',
    borderWidth: 1,
    borderColor: '#D4AF37',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  condecorationBadgeText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#FFE259',
    fontFamily: 'monospace',
  },
  condecorationDesc: {
    fontSize: 11,
    color: '#CBD5E1',
    lineHeight: 16,
  },
  openDiplomaBtn: {
    borderRadius: 12,
    overflow: 'hidden',
    marginTop: 2,
  },
  openDiplomaBtnGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 8,
  },
  openDiplomaBtnText: {
    fontSize: 11.5,
    fontWeight: '900',
    color: '#050507',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  nextLevelCard: {
    backgroundColor: 'rgba(5, 5, 8, 0.75)',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#38BDF8',
    gap: 6,
    marginTop: 4,
  },
  nextLevelHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  nextLevelIcon: {
    fontSize: 16,
  },
  nextLevelSubtitle: {
    fontSize: 8.5,
    fontFamily: 'monospace',
    color: '#38BDF8',
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  nextLevelTitleText: {
    fontSize: 12,
    fontWeight: '900',
    color: '#FFFFFF',
    fontFamily: 'serif',
  },
  comingSoonBadge: {
    backgroundColor: 'rgba(245, 158, 11, 0.2)',
    borderWidth: 1,
    borderColor: '#F59E0B',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  comingSoonText: {
    fontSize: 8,
    fontWeight: '900',
    color: '#F59E0B',
    fontFamily: 'monospace',
  },
  nextLevelBodyText: {
    fontSize: 9.5,
    color: '#94A3B8',
    lineHeight: 14,
  },
  guardianCuposBadge: {
    backgroundColor: 'rgba(212, 175, 55, 0.18)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#FFE259',
  },
  guardianCuposText: {
    fontSize: 9,
    color: '#FFE259',
    fontFamily: 'monospace',
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  guardianInviteBtn: {
    borderRadius: 12,
    overflow: 'hidden',
    marginTop: 8,
  },
  guardianInviteBtnGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 8,
  },
  guardianInviteBtnText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#050507',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  templeChambersCard: {
    backgroundColor: 'rgba(10, 14, 26, 0.85)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    padding: 14,
    marginBottom: 16,
  },
  templeChambersTitle: {
    fontSize: 10.5,
    fontFamily: 'monospace',
    fontWeight: '900',
    color: '#FFE259',
    letterSpacing: 1,
    marginBottom: 12,
    textAlign: 'center',
  },
  chambersGrid: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  chamberBtn: {
    flex: 1,
    backgroundColor: 'rgba(5, 5, 7, 0.75)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.25)',
    paddingVertical: 12,
    paddingHorizontal: 6,
    alignItems: 'center',
  },
  chamberBtnText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#F8FAFC',
    marginBottom: 2,
  },
  chamberBtnSub: {
    fontSize: 8.5,
    fontFamily: 'monospace',
    color: '#94A3B8',
    textAlign: 'center',
  },
});

