import { StyleSheet, Platform } from 'react-native';
import { Spacing, MaxContentWidth } from '@/constants/theme';

export const modalStyles = StyleSheet.create({
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2, 4, 8, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  dossierModalCard: {
    width: '100%',
    maxWidth: 460,
    maxHeight: '90%',
    backgroundColor: '#0A0F1D',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1.5,
    gap: 12,
  },
  dossierHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
    paddingBottom: 10,
  },
  dossierHeaderTag: {
    fontSize: 9,
    fontFamily: 'monospace',
    color: '#94A3B8',
    letterSpacing: 1,
  },
  dossierMainTitle: {
    fontSize: 15,
    fontWeight: '900',
    fontFamily: 'serif',
  },
  dossierTabsRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    borderRadius: 10,
    padding: 3,
    gap: 4,
  },
  dossierTabBtn: {
    flex: 1,
    paddingVertical: 7,
    alignItems: 'center',
    borderRadius: 8,
  },
  dossierTabBtnActive: {
    backgroundColor: 'rgba(212, 175, 55, 0.25)',
    borderWidth: 1,
    borderColor: '#D4AF37',
  },
  dossierTabBtnText: {
    fontSize: 10.5,
    fontWeight: '600',
    color: '#94A3B8',
    fontFamily: 'monospace',
  },
  dossierTabBtnTextActive: {
    color: '#FFE259',
    fontWeight: 'bold',
  },
  dossierContentScroll: {
    maxHeight: 380,
  },
  dossierTabContent: {
    paddingVertical: 6,
    gap: 10,
  },
  rankAuditCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.4)',
    alignItems: 'center',
    gap: 6,
  },
  rankAuditSub: {
    fontSize: 9,
    fontFamily: 'monospace',
    color: '#94A3B8',
    letterSpacing: 1,
  },
  rankAuditTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFE259',
    fontFamily: 'serif',
  },
  rankStatsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
  },
  rankStatBox: {
    alignItems: 'center',
    flex: 1,
  },
  rankStatVal: {
    fontSize: 14,
    fontWeight: '900',
    color: '#FFFFFF',
    fontFamily: 'monospace',
  },
  rankStatLbl: {
    fontSize: 8.5,
    color: '#94A3B8',
    marginTop: 2,
  },
  directivesSection: {
    gap: 6,
    marginTop: 6,
  },
  directivesTitle: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#38BDF8',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  directiveCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    borderRadius: 10,
    padding: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#38BDF8',
  },
  directiveText: {
    fontSize: 11,
    color: '#E2E8F0',
    lineHeight: 16,
  },
  feedbackSectionHeader: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#10B981',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  praiseCard: {
    backgroundColor: 'rgba(6, 78, 59, 0.25)',
    borderRadius: 10,
    padding: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#10B981',
  },
  praiseText: {
    fontSize: 11,
    color: '#A7F3D0',
    lineHeight: 16,
  },
  scoldCard: {
    backgroundColor: 'rgba(127, 29, 29, 0.25)',
    borderRadius: 10,
    padding: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#EF4444',
  },
  scoldText: {
    fontSize: 11,
    color: '#FECACA',
    lineHeight: 16,
  },
  pillarAdherenceCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    borderRadius: 12,
    padding: 12,
    gap: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    marginTop: 6,
  },
  pillarAdherenceTitle: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#FFE259',
    fontFamily: 'monospace',
    marginBottom: 4,
  },
  pillarAdherenceLine: {
    fontSize: 10.5,
    color: '#CBD5E1',
    fontFamily: 'monospace',
  },
  auditIntroText: {
    fontSize: 10.5,
    color: '#94A3B8',
    fontStyle: 'italic',
    marginBottom: 4,
  },
  dayAuditRow: {
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    gap: 4,
  },
  dayAuditRowSuccess: {
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  dayAuditRowFailed: {
    backgroundColor: 'rgba(20, 10, 15, 0.85)',
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  dayAuditTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dayAuditDayTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'monospace',
  },
  dayAuditScoreBadge: {
    fontSize: 11,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  dayAuditPillarsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 2,
  },
  dayAuditPillarTag: {
    fontSize: 12,
    opacity: 0.35,
  },
  dayAuditPillarTagActive: {
    opacity: 1,
  },
  dayAuditPassedCount: {
    fontSize: 9.5,
    color: '#94A3B8',
    fontFamily: 'monospace',
    marginLeft: 4,
  },
  dayAuditVerdictText: {
    fontSize: 10,
    color: '#94A3B8',
    lineHeight: 14,
  },
  dossierActionsRow: {
    gap: 8,
    marginTop: 4,
  },
  copyDecreeBtn: {
    backgroundColor: 'rgba(212, 175, 55, 0.2)',
    borderWidth: 1,
    borderColor: '#D4AF37',
    paddingVertical: 9,
    borderRadius: 10,
    alignItems: 'center',
  },
  copyDecreeBtnText: {
    color: '#FFE259',
    fontWeight: 'bold',
    fontSize: 11,
    fontFamily: 'monospace',
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#0F172A',
    borderRadius: 18,
    padding: 20,
    borderWidth: 1.5,
    gap: 12,
    alignItems: 'center',
  },
  modalCardSuccess: {
    borderColor: '#FFE259',
  },
  modalCardScold: {
    borderColor: '#EF4444',
  },
  modalEmblem: {
    fontSize: 32,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '900',
    fontFamily: 'serif',
  },
  modalMessage: {
    fontSize: 12,
    color: '#E2E8F0',
    textAlign: 'center',
    lineHeight: 18,
  },
  resetCycleBtn: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    borderWidth: 1,
    borderColor: '#EF4444',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    width: '100%',
    alignItems: 'center',
  },
  resetCycleBtnText: {
    color: '#FCA5A5',
    fontWeight: 'bold',
    fontSize: 10.5,
    fontFamily: 'monospace',
  },
  closeModalBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
    width: '100%',
    alignItems: 'center',
  },
  closeModalBtnText: {
    color: '#94A3B8',
    fontWeight: 'bold',
    fontSize: 11,
    fontFamily: 'monospace',
  },
  diplomaBannerBtn: {
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: '#FFE259',
    marginVertical: 4,
    shadowColor: '#FFE259',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
  },
  diplomaBannerGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    gap: 12,
  },
  diplomaBannerTag: {
    fontSize: 9,
    fontWeight: '900',
    color: '#050507',
    fontFamily: 'monospace',
    letterSpacing: 1,
  },
  diplomaBannerTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#050507',
    fontFamily: 'serif',
    letterSpacing: 1,
    marginTop: 2,
  },
  diplomaBannerSub: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#3B2F04',
    marginTop: 2,
  },
  claimDiplomaBtn: {
    borderRadius: 12,
    overflow: 'hidden',
    marginTop: 4,
  },
  claimDiplomaGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 8,
  },
  claimDiplomaText: {
    fontSize: 11.5,
    fontWeight: '900',
    color: '#050507',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  diplomaLockedCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: 'rgba(245, 158, 11, 0.35)',
    padding: 14,
    marginVertical: 4,
    gap: 10,
  },
  diplomaLockedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  diplomaLockedTag: {
    fontSize: 8.5,
    fontFamily: 'monospace',
    color: '#94A3B8',
    letterSpacing: 0.5,
    fontWeight: 'bold',
  },
  diplomaLockedTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: '#F59E0B',
    fontFamily: 'serif',
    marginTop: 1,
  },
  diplomaLockBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.4)',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  diplomaLockBadgeText: {
    fontSize: 9.5,
    fontWeight: 'bold',
    color: '#F59E0B',
    fontFamily: 'monospace',
  },
  diplomaProgressBoxes: {
    flexDirection: 'row',
    gap: 8,
  },
  diplomaProgBox: {
    flex: 1,
    backgroundColor: 'rgba(5, 5, 8, 0.6)',
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  diplomaProgVal: {
    fontSize: 13,
    fontWeight: '900',
    color: '#FFFFFF',
    fontFamily: 'monospace',
  },
  diplomaProgLbl: {
    fontSize: 8,
    color: '#94A3B8',
    marginTop: 2,
    marginBottom: 6,
  },
  diplomaMiniTrack: {
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  diplomaMiniFill: {
    height: '100%',
    borderRadius: 2,
  },
  diplomaLockedNotice: {
    fontSize: 9.5,
    color: '#94A3B8',
    lineHeight: 14,
    fontStyle: 'italic',
  },
  lockedModalReqsBox: {
    width: '100%',
    backgroundColor: 'rgba(5, 5, 8, 0.6)',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    gap: 10,
    marginVertical: 8,
  },
  lockedReqRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  lockedReqTitle: {
    fontSize: 10.5,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  lockedReqDesc: {
    fontSize: 9.5,
    color: '#94A3B8',
    marginTop: 2,
    fontFamily: 'monospace',
  },
  closeLockedModalBtn: {
    backgroundColor: '#F59E0B',
    borderRadius: 10,
    paddingVertical: 10,
    width: '100%',
    alignItems: 'center',
    marginTop: 6,
  },
  closeLockedModalBtnText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#050507',
    fontFamily: 'monospace',
  },
});
