import { StyleSheet, Platform } from 'react-native';
import { Spacing, MaxContentWidth } from '@/constants/theme';
import { modalStyles } from './progress.modal.styles';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  safeArea: {
    flex: 1,
    maxWidth: MaxContentWidth,
    alignSelf: 'center',
    width: '100%',
  },
  scrollContent: {
    paddingHorizontal: Spacing.four,
    paddingTop: Spacing.two,
    paddingBottom: Spacing.six,
    gap: Spacing.three,
  },
  header: {
    alignItems: 'center',
    marginTop: Spacing.two,
    marginBottom: Spacing.one,
  },
  tierBadge: {
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
    borderWidth: 1,
    borderColor: '#FFE259',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 3,
    marginBottom: 6,
  },
  tierBadgeText: {
    fontSize: 9.5,
    fontWeight: '900',
    color: '#FFE259',
    letterSpacing: 2,
    fontFamily: 'monospace',
  },
  title: {
    fontSize: 24,
    fontFamily: 'serif',
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 2,
  },
  pathSubheader: {
    fontSize: 11,
    color: '#D4AF37',
    fontFamily: 'monospace',
    fontWeight: 'bold',
    marginTop: 2,
  },
  pactCard: {
    backgroundColor: 'rgba(14, 20, 36, 0.95)',
    borderWidth: 1.5,
    borderColor: '#D4AF37',
    borderRadius: 18,
    padding: 16,
    gap: 8,
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  pactCardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pactStatusBadge: {
    backgroundColor: 'rgba(212, 175, 55, 0.18)',
    borderWidth: 1,
    borderColor: '#FFE259',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  pactStatusBadgeText: {
    fontSize: 9,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    color: '#FFE259',
    letterSpacing: 1,
  },
  pactDayCounterText: {
    fontSize: 12.5,
    fontFamily: 'monospace',
    fontWeight: '900',
    color: '#38BDF8',
  },
  pactStartDateText: {
    fontSize: 10,
    color: '#94A3B8',
    fontFamily: 'monospace',
  },
  pactDescText: {
    fontSize: 11,
    color: '#CBD5E1',
    lineHeight: 16,
  },
  startPactBtn: {
    borderRadius: 12,
    overflow: 'hidden',
    marginTop: 4,
  },
  startPactGradient: {
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  startPactBtnText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#050507',
    fontFamily: 'monospace',
    letterSpacing: 1,
  },
  confirmPactBtn: {
    borderRadius: 12,
    overflow: 'hidden',
    width: '100%',
    marginTop: 6,
  },
  confirmPactBtnText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#050507',
    fontFamily: 'monospace',
    letterSpacing: 1,
    textAlign: 'center',
  },
  mandatoryCard: {
    backgroundColor: 'rgba(14, 20, 36, 0.95)',
    borderWidth: 1.5,
    borderColor: 'rgba(212, 175, 55, 0.55)',
    borderRadius: 18,
    padding: 16,
    gap: 10,
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  mandatoryHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  mandatoryBadge: {
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
    borderWidth: 1,
    borderColor: '#FFE259',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  mandatoryBadgeText: {
    fontSize: 9,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    color: '#FFE259',
    letterSpacing: 1,
  },
  statusText: {
    fontSize: 10,
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  equipSelectorRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 2,
  },
  equipChip: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
    borderRadius: 8,
    paddingVertical: 6,
    alignItems: 'center',
  },
  equipChipActive: {
    backgroundColor: 'rgba(212, 175, 55, 0.22)',
    borderColor: '#FFE259',
  },
  equipChipText: {
    fontSize: 9.5,
    color: '#94A3B8',
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  equipChipTextActive: {
    color: '#FFE259',
  },
  mandatoryTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#FFFFFF',
    fontFamily: 'serif',
  },
  mandatoryFocus: {
    fontSize: 11,
    color: '#D4AF37',
    fontFamily: 'monospace',
    marginTop: 3,
  },
  immutableNoticeBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.2)',
    borderRadius: 8,
    padding: 8,
  },
  immutableNoticeText: {
    fontSize: 10,
    color: '#CBD5E1',
    fontStyle: 'italic',
    lineHeight: 14,
  },
  exerciseList: {
    gap: 8,
    marginTop: 4,
  },
  exerciseItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.15)',
    borderRadius: 12,
    padding: 10,
  },
  exerciseItemRowChecked: {
    borderColor: 'rgba(16, 185, 129, 0.45)',
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
  },
  checkCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkCircleChecked: {
    backgroundColor: '#10B981',
    borderColor: '#10B981',
  },
  checkMarkText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'monospace',
  },
  exerciseName: {
    fontSize: 12.5,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  exerciseNameChecked: {
    color: '#6EE7B7',
    textDecorationLine: 'line-through',
  },
  exerciseMetaRow: {
    flexDirection: 'row',
    gap: 4,
    marginTop: 2,
  },
  exerciseSeries: {
    fontSize: 10,
    color: '#D4AF37',
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  exerciseRpe: {
    fontSize: 10,
    color: '#94A3B8',
    fontFamily: 'monospace',
  },
  exerciseGroup: {
    fontSize: 10,
    color: '#38BDF8',
    fontFamily: 'monospace',
  },
  exerciseCue: {
    fontSize: 9.5,
    color: '#94A3B8',
    fontStyle: 'italic',
    marginTop: 2,
  },
  techGuideBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FFE259',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  techGuideBtnText: {
    fontSize: 9.5,
    fontWeight: '900',
    color: '#050507',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  sealWorkoutBtn: {
    marginTop: 6,
    borderRadius: 12,
    overflow: 'hidden',
  },
  sealWorkoutGradient: {
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sealWorkoutText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#050507',
    fontFamily: 'monospace',
    letterSpacing: 1,
  },
  optionalHintText: {
    fontSize: 9.5,
    color: '#94A3B8',
    textAlign: 'center',
    fontFamily: 'monospace',
    marginTop: 4,
  },
  todayCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.90)',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    gap: 10,
  },
  todayCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  scorePill: {
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
    borderWidth: 1,
    borderColor: '#FFE259',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignItems: 'center',
    flexDirection: 'row',
  },
  scoreText: {
    fontSize: 18,
    fontWeight: '900',
    color: '#FFE259',
    fontFamily: 'monospace',
  },
  scoreMax: {
    fontSize: 10,
    color: '#D4AF37',
    fontFamily: 'monospace',
  },
  todayGradeLabel: {
    fontSize: 9.5,
    color: '#94A3B8',
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  todayGradeStatus: {
    fontSize: 13,
    fontWeight: 'bold',
    fontFamily: 'serif',
  },
  pillarsGridTitle: {
    fontSize: 10.5,
    color: '#D4AF37',
    fontFamily: 'monospace',
    fontWeight: 'bold',
    marginTop: 4,
    letterSpacing: 0.5,
  },
  pillarsListGrid: {
    gap: 6,
  },
  pillarRowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.12)',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    overflow: 'hidden',
  },
  pillarRowCardActive: {
    borderColor: 'rgba(16, 185, 129, 0.45)',
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
  },
  pillarRowIcon: {
    fontSize: 15,
  },
  pillarRowName: {
    fontSize: 11.5,
    fontWeight: 'bold',
    color: '#FFFFFF',
    flexShrink: 1,
  },
  pillarRowDesc: {
    fontSize: 9.5,
    color: '#94A3B8',
    fontFamily: 'monospace',
    marginTop: 1,
    flexShrink: 1,
  },
  pillarRowPts: {
    fontSize: 10.5,
    fontWeight: 'bold',
    color: '#94A3B8',
    fontFamily: 'monospace',
    flexShrink: 0,
  },
  pillarRowPtsActive: {
    color: '#10B981',
  },
  todayVerdictText: {
    fontSize: 10.5,
    color: '#CBD5E1',
    fontStyle: 'italic',
    lineHeight: 14,
    flexShrink: 1,
  },
  adherenceCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.90)',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    gap: 8,
    overflow: 'hidden',
  },
  adherenceHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  adherenceTitle: {
    fontSize: 10,
    color: '#D4AF37',
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  adherencePercent: {
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  progressBarTrack: {
    height: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  adherenceSub: {
    fontSize: 10,
    color: '#94A3B8',
    fontFamily: 'monospace',
  },
  constellationCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.90)',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    gap: 8,
  },
  constellationTitle: {
    fontSize: 10,
    color: '#FFE259',
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  constellationDesc: {
    fontSize: 10,
    color: '#94A3B8',
    lineHeight: 14,
  },
  starMap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'center',
    marginTop: 6,
  },
  starContainer: {
    alignItems: 'center',
    width: 24,
  },
  todayContainer: {
    transform: [{ scale: 1.15 }],
  },
  star: {
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  starDayLabel: {
    fontSize: 7.5,
    color: '#64748B',
    fontFamily: 'monospace',
    marginTop: 2,
  },
  judgmentBtn: {
    backgroundColor: '#D4AF37',
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 4,
  },
  judgmentBtnInner: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  judgmentBtnText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#050507',
    fontFamily: 'monospace',
    letterSpacing: 1,
  },

  ...modalStyles,
});
