import { StyleSheet, Platform } from 'react-native';
import { Spacing, MaxContentWidth } from '@/constants/theme';
import { trainerModalStyles } from './trainer.modal.styles';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  content: {
    paddingHorizontal: Spacing.four,
    maxWidth: MaxContentWidth,
    alignSelf: 'center',
    width: '100%',
    paddingTop: Spacing.four,
    paddingBottom: Spacing.four,
  },
  header: {
    marginTop: Spacing.two,
    marginBottom: Spacing.two,
  },
  headerTopBadgeRow: {
    marginBottom: 8,
  },
  moduleBadgeContainer: {
    backgroundColor: 'rgba(56, 189, 248, 0.12)',
    borderWidth: 1,
    borderColor: '#38BDF8',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: 'flex-start',
  },
  moduleBadgeText: {
    fontSize: 9.5,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    color: '#38BDF8',
    letterSpacing: 1,
  },
  headerMainRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  label: {
    fontSize: 10,
    textTransform: 'uppercase',
    color: '#38BDF8',
    letterSpacing: 2,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  title: {
    fontSize: 24,
    fontFamily: 'serif',
    marginTop: 4,
    textTransform: 'uppercase',
    fontWeight: '900',
    color: '#FFFFFF',
    textShadowColor: 'rgba(212, 175, 55, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  metaSub: {
    fontSize: 12,
    color: '#FFE259',
    marginTop: 4,
    fontWeight: 'bold',
  },
  amorFatiBtn: {
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  amorFatiText: {
    fontSize: 11,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  infoBanner: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.25)',
    borderRadius: 10,
    padding: 10,
    marginTop: 10,
  },
  infoBannerText: {
    fontSize: 10.5,
    color: '#CBD5E1',
    fontStyle: 'italic',
    lineHeight: 15,
  },

  // TOOLBAR DE PERSONALIZACIÓN
  customActionToolbar: {
    flexDirection: 'row',
    gap: 8,
    marginVertical: Spacing.two,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  actionToolBtnPrimary: {
    flex: 1.2,
    minWidth: 130,
    borderRadius: 10,
    overflow: 'hidden',
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 3,
  },
  actionToolGradient: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionToolPrimaryText: {
    color: '#050507',
    fontWeight: '900',
    fontFamily: 'monospace',
    fontSize: 11,
    letterSpacing: 0.5,
  },
  actionToolBtnSecondary: {
    flex: 1,
    minWidth: 95,
    backgroundColor: 'rgba(212, 175, 55, 0.12)',
    borderWidth: 1.5,
    borderColor: 'rgba(212, 175, 55, 0.40)',
    borderRadius: 10,
    paddingVertical: 9,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionToolSecondaryText: {
    color: '#FFE259',
    fontWeight: 'bold',
    fontFamily: 'monospace',
    fontSize: 11,
    letterSpacing: 0.5,
  },
  actionToolBtnIcon: {
    width: 40,
    height: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionToolIconText: {
    fontSize: 16,
  },

  // PROKOPTON BANNER
  prokoptonBanner: {
    backgroundColor: 'rgba(212, 175, 55, 0.10)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: Spacing.two,
  },
  prokoptonBannerTitle: {
    fontSize: 12,
    fontWeight: '900',
    color: '#FFE259',
    fontFamily: 'serif',
    letterSpacing: 0.5,
  },
  prokoptonBannerSub: {
    fontSize: 11,
    color: '#CBD5E1',
    marginTop: 1,
  },
  prokoptonTag: {
    backgroundColor: '#D4AF37',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  prokoptonTagText: {
    color: '#050507',
    fontSize: 9,
    fontWeight: '900',
    fontFamily: 'monospace',
    letterSpacing: 1,
  },

  // GENERATOR BUTTON
  generatorMainTouch: {
    marginBottom: Spacing.two,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  generatorMainGradient: {
    padding: Spacing.three,
  },
  generatorBtnTitle: {
    fontSize: 12.5,
    fontWeight: '900',
    color: '#FFE259',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  generatorBtnSub: {
    fontSize: 10.5,
    color: '#94A3B8',
    fontFamily: 'sans-serif',
    marginTop: 2,
  },

  // READINESS CARD
  readinessCard: {
    padding: Spacing.three,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    backgroundColor: 'rgba(13, 17, 28, 0.95)',
    marginBottom: Spacing.two,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  readinessHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  cardSectionTitle: {
    fontSize: 12.5,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    textTransform: 'uppercase',
    color: '#FFE259',
  },
  readinessToggleBtnText: {
    fontSize: 12,
    color: '#38BDF8',
    fontWeight: 'bold',
  },
  readinessSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  scoreBadge: {
    flexDirection: 'row',
    alignItems: 'baseline',
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.4)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  scoreNumber: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFE259',
  },
  scoreLabel: {
    fontSize: 12,
    color: '#FFE259',
    marginLeft: 2,
  },
  readinessMetricsText: {
    fontSize: 12,
    color: '#E2E8F0',
  },
  readinessVerdictText: {
    fontSize: 11,
    color: '#38BDF8',
    marginTop: 2,
    fontStyle: 'italic',
  },
  readinessSliders: {
    marginTop: 8,
    gap: 8,
  },
  sliderRow: {
    gap: 4,
  },
  sliderLabel: {
    fontSize: 11.5,
    fontWeight: '600',
    color: '#E2E8F0',
  },
  miniBtn: {
    width: 30,
    height: 30,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.25)',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniBtnActive: {
    backgroundColor: '#D4AF37',
    borderColor: '#D4AF37',
  },
  miniBtnTextActive: {
    color: '#050507',
    fontWeight: 'bold',
  },
  miniBtnTextInactive: {
    color: '#94A3B8',
  },
  saveReadinessBtn: {
    backgroundColor: '#D4AF37',
    paddingVertical: 9,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 6,
  },
  saveReadinessBtnText: {
    color: '#050507',
    fontWeight: '900',
    fontSize: 12,
  },

  // VOLUME BANNER
  volumeBanner: {
    padding: Spacing.three,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    backgroundColor: 'rgba(13, 17, 28, 0.95)',
    marginBottom: Spacing.two,
  },
  volumeLabel: {
    fontSize: 11,
    color: '#94A3B8',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  volumeValue: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFE259',
    fontFamily: 'serif',
  },
  volumeSubLabel: {
    fontSize: 10,
    color: '#94A3B8',
  },
  volumeSubValue: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FDE68A',
  },

  // LIST HEADER
  listHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: Spacing.two,
    marginBottom: Spacing.two,
  },
  listHeaderTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    color: '#FFE259',
    letterSpacing: 1,
  },
  listAddQuickBtn: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#38BDF8',
  },

  // LIST & CARDS
  list: {
    gap: Spacing.two,
  },
  emptyListCard: {
    padding: Spacing.four,
    borderRadius: 14,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: 'rgba(212, 175, 55, 0.4)',
    backgroundColor: 'rgba(13, 17, 28, 0.8)',
    alignItems: 'center',
    gap: 8,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFE259',
    fontFamily: 'serif',
  },
  emptySub: {
    fontSize: 12,
    color: '#94A3B8',
    textAlign: 'center',
    lineHeight: 16,
  },
  emptyAddBtn: {
    backgroundColor: '#D4AF37',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 4,
  },
  emptyAddBtnText: {
    color: '#050507',
    fontWeight: '900',
    fontFamily: 'monospace',
    fontSize: 12,
  },

  card: {
    padding: Spacing.three,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: 'rgba(212, 175, 55, 0.40)',
    backgroundColor: 'rgba(13, 17, 28, 0.96)',
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
    overflow: 'hidden',
  },
  cardTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  cardHeaderTouch: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  checkbox: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  checkboxDone: {
    backgroundColor: '#D4AF37',
    borderColor: '#D4AF37',
  },
  checkboxPending: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(212, 175, 55, 0.5)',
  },
  checkboxCheck: {
    fontSize: 15,
    color: '#050507',
    fontWeight: '900',
    textAlign: 'center',
  },

  // HIGH CONTRAST EXERCISE TITLE & BADGES
  exerciseName: {
    fontSize: 15.5,
    fontWeight: '900',
    fontFamily: 'serif',
    color: '#FFFFFF', // High-contrast crisp white!
    letterSpacing: 0.3,
    lineHeight: 22,
    flexShrink: 1,
  },
  exerciseNameDone: {
    textDecorationLine: 'line-through',
    opacity: 0.6,
    color: '#94A3B8',
  },
  cardMetaAndControlsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  exerciseBadgesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    flexShrink: 1,
  },
  setsBadge: {
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.40)',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignSelf: 'flex-start',
  },
  setsBadgeText: {
    fontSize: 11,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    color: '#FFE259',
  },
  muscleBadge: {
    backgroundColor: 'rgba(56, 189, 248, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.35)',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignSelf: 'flex-start',
  },
  muscleBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    color: '#38BDF8',
  },

  // EXERCISE CONTROLS (EDIT, REORDER, DELETE)
  exerciseControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
  },
  iconCtrlBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconCtrlDelete: {
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  iconCtrlText: {
    fontSize: 12,
  },

  // RPE SELECTOR
  rpeContainer: {
    marginTop: Spacing.two,
    paddingTop: Spacing.two,
    borderTopWidth: 1,
    borderTopColor: 'rgba(212, 175, 55, 0.15)',
  },
  rpeSectionLabel: {
    fontSize: 10.5,
    color: '#94A3B8',
    marginBottom: 6,
    fontFamily: 'monospace',
  },
  rpeButton: {
    width: 32,
    height: 32,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.25)',
    backgroundColor: 'rgba(212, 175, 55, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rpeButtonActive: {
    backgroundColor: '#D4AF37',
    borderColor: '#D4AF37',
  },
  rpeButtonTextActive: {
    color: '#050507',
    fontWeight: 'bold',
  },
  rpeButtonTextInactive: {
    color: '#CBD5E1',
    fontSize: 12,
  },
  progressionBox: {
    marginTop: 8,
    padding: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(212, 175, 55, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.25)',
  },
  progressionTipText: {
    fontSize: 11,
    color: '#FDE68A',
    fontStyle: 'italic',
    lineHeight: 15,
  },

  // FINISH BUTTON
  finishBtnTouch: {
    marginTop: Spacing.four,
    marginBottom: Spacing.three,
  },
  finishBtnContainer: {
    marginTop: Spacing.four,
    marginBottom: Spacing.three,
  },
  finishBtnGradient: {
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 4,
  },
  finishBtnText: {
    color: '#050507',
    fontWeight: '900',
    fontSize: 13.5,
    letterSpacing: 1,
    fontFamily: 'monospace',
  },

  // MODAL STYLES

  ...trainerModalStyles,
});
