import { StyleSheet, Platform, Dimensions } from 'react-native';
import { Spacing, MaxContentWidth } from '@/constants/theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    maxWidth: MaxContentWidth,
    alignSelf: 'center',
    width: '100%',
  },
  scrollContent: {
    paddingHorizontal: Spacing.four,
    paddingTop: Spacing.two,
    paddingBottom: Spacing.six,
    gap: Spacing.three,
  },
  header: {
    alignItems: 'center',
    marginTop: Spacing.two,
    marginBottom: Spacing.one,
  },
  badgeTier: {
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
    borderWidth: 1,
    borderColor: '#FFE259',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 3,
    marginBottom: 6,
  },
  badgeTierText: {
    fontSize: 9.5,
    fontWeight: '900',
    color: '#FFE259',
    letterSpacing: 2,
    fontFamily: 'monospace',
  },
  title: {
    fontSize: 24,
    fontFamily: 'serif',
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 2,
  },
  subtitle: {
    fontSize: 11,
    color: '#D4AF37',
    fontFamily: 'monospace',
    fontWeight: 'bold',
    marginTop: 2,
  },
  ctaCaptureBtn: {
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
  },
  ctaCaptureGradient: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  ctaCaptureText: {
    fontSize: 12,
    fontWeight: '900',
    color: '#050507',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  ctaCaptureSub: {
    fontSize: 9.5,
    color: '#3B2800',
    fontFamily: 'monospace',
    marginTop: 2,
  },
  cardContainer: {
    backgroundColor: 'rgba(15, 23, 42, 0.90)',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    gap: 12,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionBadge: {
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
    borderWidth: 1,
    borderColor: '#FFE259',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  sectionBadgeText: {
    fontSize: 9,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    color: '#FFE259',
    letterSpacing: 1,
  },
  cardHeaderTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'monospace',
  },
  comparatorDesc: {
    fontSize: 11,
    color: '#CBD5E1',
    lineHeight: 16,
  },
  chipsScroll: {
    flexDirection: 'row',
    gap: 6,
    paddingVertical: 2,
  },
  zoneChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  zoneChipActive: {
    backgroundColor: 'rgba(212, 175, 55, 0.22)',
    borderColor: '#FFE259',
  },
  zoneChipText: {
    fontSize: 10,
    color: '#94A3B8',
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  zoneChipTextActive: {
    color: '#FFE259',
  },
  comparatorDualContainer: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(5, 5, 7, 0.6)',
    borderRadius: 14,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.2)',
  },
  comparatorSide: {
    flex: 1,
    alignItems: 'center',
    gap: 6,
  },
  sideHeaderBadge: {
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
    borderWidth: 1,
    borderColor: '#D4AF37',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  sideHeaderBadgeAfter: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderColor: '#10B981',
  },
  sideBadgeText: {
    fontSize: 8.5,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    color: '#FFE259',
  },
  comparatorImageWrapper: {
    width: '100%',
    aspectRatio: 3 / 4,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    backgroundColor: '#000000',
  },
  comparatorImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  sideMetaText: {
    fontSize: 9.5,
    color: '#CBD5E1',
    fontFamily: 'monospace',
  },
  comparatorDivider: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(212, 175, 55, 0.25)',
    borderWidth: 1,
    borderColor: '#FFE259',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dividerVsText: {
    fontSize: 8.5,
    fontWeight: '900',
    color: '#FFE259',
    fontFamily: 'monospace',
  },
  emptyComparatorBox: {
    backgroundColor: 'rgba(5, 5, 7, 0.5)',
    borderRadius: 14,
    padding: 20,
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  emptyComparatorTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    fontFamily: 'serif',
  },
  emptyComparatorDesc: {
    fontSize: 10,
    color: '#94A3B8',
    textAlign: 'center',
    lineHeight: 14,
  },
  galleryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  galleryCard: {
    width: (SCREEN_WIDTH - 32 - 32 - 10) / 2 > 160 ? (SCREEN_WIDTH - 32 - 32 - 10) / 2 : 160,
    aspectRatio: 3 / 4,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.3)',
    backgroundColor: '#000000',
  },
  galleryCardImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  galleryCardOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 8,
    justifyContent: 'flex-end',
    gap: 2,
  },
  galleryCardBadgeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dayTagBadge: {
    backgroundColor: 'rgba(212, 175, 55, 0.35)',
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 1,
  },
  dayTagText: {
    fontSize: 8.5,
    fontWeight: 'bold',
    color: '#FFE259',
    fontFamily: 'monospace',
  },
  galleryZoneTag: {
    fontSize: 8.5,
    color: '#CBD5E1',
    fontFamily: 'monospace',
  },
  galleryCardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 2,
  },
  galleryDateText: {
    fontSize: 8,
    color: '#94A3B8',
  },
  galleryWeightText: {
    fontSize: 8.5,
    color: '#38BDF8',
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  emptyGalleryBox: {
    padding: 24,
    alignItems: 'center',
    gap: 6,
  },
  emptyGalleryText: {
    fontSize: 11,
    color: '#94A3B8',
    textAlign: 'center',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2, 4, 8, 0.88)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  captureModalCard: {
    width: '100%',
    maxWidth: 440,
    backgroundColor: '#0F172A',
    borderRadius: 20,
    padding: 18,
    borderWidth: 1.5,
    borderColor: '#D4AF37',
    gap: 12,
  },
  captureModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
    paddingBottom: 10,
  },
  captureModalTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#FFE259',
    fontFamily: 'monospace',
    letterSpacing: 1,
  },
  closeModalCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalFieldLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#D4AF37',
    fontFamily: 'monospace',
    marginTop: 10,
    marginBottom: 6,
  },
  zoneSelectorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  modalZoneChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.2)',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  modalZoneChipSelected: {
    backgroundColor: 'rgba(212, 175, 55, 0.25)',
    borderColor: '#FFE259',
  },
  modalZoneIcon: {
    fontSize: 12,
  },
  modalZoneName: {
    fontSize: 9.5,
    color: '#94A3B8',
    fontFamily: 'monospace',
  },
  modalZoneNameSelected: {
    color: '#FFE259',
    fontWeight: 'bold',
  },
  zoneDescriptionText: {
    fontSize: 9.5,
    color: '#CBD5E1',
    fontStyle: 'italic',
    marginTop: 4,
    lineHeight: 15,
  },
  takePhotoBox: {
    backgroundColor: 'rgba(5, 5, 7, 0.7)',
    borderWidth: 1.5,
    borderColor: 'rgba(212, 175, 55, 0.4)',
    borderStyle: 'dashed',
    borderRadius: 14,
    padding: 24,
    alignItems: 'center',
    gap: 6,
  },
  takePhotoTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#FFE259',
    fontFamily: 'monospace',
    textAlign: 'center',
  },
  takePhotoSub: {
    fontSize: 9,
    color: '#94A3B8',
    textAlign: 'center',
  },
  previewContainer: {
    alignItems: 'center',
    gap: 8,
  },
  previewImage: {
    width: '100%',
    height: 220,
    borderRadius: 12,
    resizeMode: 'cover',
    borderWidth: 1,
    borderColor: '#10B981',
  },
  retakeBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  retakeBtnText: {
    fontSize: 10,
    color: '#FFFFFF',
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  notesInput: {
    backgroundColor: 'rgba(5, 5, 7, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
    borderRadius: 10,
    padding: 10,
    color: '#FFFFFF',
    fontSize: 11,
    minHeight: 50,
    textAlignVertical: 'top',
  },
  metaRowInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 8,
    padding: 8,
    marginTop: 8,
  },
  metaRowText: {
    fontSize: 10,
    color: '#94A3B8',
    fontFamily: 'monospace',
  },
  saveSnapshotBtn: {
    borderRadius: 12,
    overflow: 'hidden',
    marginTop: 12,
    marginBottom: 10,
  },
  saveSnapshotGradient: {
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveSnapshotBtnText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#FFFFFF',
    fontFamily: 'monospace',
    letterSpacing: 1,
  },
  lightboxBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 14,
  },
  lightboxCard: {
    width: '100%',
    maxWidth: 480,
    backgroundColor: '#0F172A',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.4)',
    gap: 12,
  },
  lightboxHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  lightboxDayText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#FFE259',
    fontFamily: 'monospace',
  },
  lightboxDateText: {
    fontSize: 10,
    color: '#94A3B8',
  },
  lightboxImageContainer: {
    width: '100%',
    height: 380,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#000000',
  },
  lightboxImage: {
    width: '100%',
    height: '100%',
  },
  lightboxNotesBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 8,
    padding: 8,
  },
  lightboxNotesText: {
    fontSize: 11,
    color: '#E2E8F0',
    fontStyle: 'italic',
  },
  lightboxActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  deletePhotoBtn: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderWidth: 1,
    borderColor: '#EF4444',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  deletePhotoText: {
    fontSize: 10,
    color: '#FCA5A5',
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  closeLightboxBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    flex: 1,
    alignItems: 'center',
  },
  closeLightboxText: {
    fontSize: 10.5,
    color: '#FFFFFF',
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
});
