import { StyleSheet, Platform } from 'react-native';
import { Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: 'rgba(13, 17, 28, 0.94)',
    borderRadius: 16,
    padding: Spacing.three,
    marginBottom: Spacing.three,
    borderWidth: 1.5,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    shadowColor: '#D4AF37',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  badge: {
    fontSize: 9,
    fontFamily: 'monospace',
    color: '#D4AF37',
    letterSpacing: 1.5,
    fontWeight: 'bold',
  },
  deviceName: {
    fontSize: 13.5,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    color: '#F8FAFC',
    marginTop: 1,
  },
  statusTag: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    gap: 6,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  statusText: {
    fontSize: 9.5,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  promptText: {
    fontSize: 11.5,
    color: '#CBD5E1',
    lineHeight: 17,
    marginVertical: Spacing.two,
  },
  metricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: Spacing.two,
    marginVertical: Spacing.two,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.18)',
  },
  metricItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metricLabel: {
    fontSize: 8.5,
    fontFamily: 'monospace',
    color: '#94A3B8',
  },
  metricValue: {
    fontSize: 12.5,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    color: '#FFE259',
  },
  actionsRow: {
    flexDirection: 'row',
    gap: Spacing.two,
    marginTop: Spacing.two,
  },
  btn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.two + 2,
    paddingHorizontal: Spacing.two,
    borderRadius: 10,
    borderWidth: 1,
  },
  btnSmartwatch: {
    backgroundColor: '#D4AF37',
    borderColor: '#D4AF37',
  },
  btnSmartwatchText: {
    color: '#050507',
    fontSize: 11,
    fontWeight: '900',
    fontFamily: 'monospace',
    letterSpacing: 0.3,
  },
  btnGoogleHealth: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderColor: 'rgba(16, 185, 129, 0.40)',
  },
  btnGoogleHealthText: {
    color: '#34D399',
    fontSize: 11,
    fontWeight: '900',
    fontFamily: 'monospace',
    letterSpacing: 0.3,
  },
  btnSyncNow: {
    backgroundColor: '#FFE259',
    borderColor: '#FFE259',
  },
  btnSyncNowText: {
    color: '#050507',
    fontSize: 11,
    fontWeight: '900',
    fontFamily: 'monospace',
  },
  btnDisconnect: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderColor: 'rgba(239, 68, 68, 0.40)',
  },
  btnDisconnectText: {
    color: '#F87171',
    fontSize: 11,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(5, 5, 7, 0.92)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.four,
  },
  modalContent: {
    width: '100%',
    maxWidth: 440,
    backgroundColor: '#0A0D16',
    padding: Spacing.four,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: 'rgba(212, 175, 55, 0.45)',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: Spacing.three,
  },
  modalBadge: {
    fontSize: 9,
    fontFamily: 'monospace',
    color: '#D4AF37',
    fontWeight: '900',
    letterSpacing: 1.5,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    color: '#FFFFFF',
    marginTop: 2,
  },
  modalCloseBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseBtnText: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: 'bold',
  },
  modalInstructionText: {
    fontSize: 11.5,
    color: '#CBD5E1',
    lineHeight: 17,
    marginBottom: Spacing.three,
  },
  brandOptionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    padding: Spacing.three,
    marginBottom: Spacing.two,
    gap: 12,
  },
  brandOptionCardActive: {
    borderColor: '#FFE259',
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
  },
  brandIconBox: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandNameText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  brandModelsText: {
    fontSize: 10,
    color: '#94A3B8',
    fontFamily: 'monospace',
    marginTop: 2,
  },
  connectArrowText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#FFE259',
    fontFamily: 'monospace',
  },
  securityNoteBox: {
    backgroundColor: 'rgba(212, 175, 55, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.20)',
    borderRadius: 10,
    padding: Spacing.three,
    marginTop: Spacing.two,
  },
  securityNoteText: {
    fontSize: 10,
    color: '#FDE68A',
    lineHeight: 15,
    fontFamily: 'monospace',
  },
  healthBannerBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(16, 185, 129, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.30)',
    borderRadius: 14,
    padding: Spacing.three,
    marginBottom: Spacing.three,
  },
  healthBannerTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#34D399',
    marginTop: 6,
    fontFamily: 'monospace',
  },
  healthBannerDesc: {
    fontSize: 11,
    color: '#CBD5E1',
    textAlign: 'center',
    marginTop: 4,
    lineHeight: 16,
  },
  permissionList: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 10,
    padding: Spacing.three,
    gap: 6,
    marginBottom: Spacing.three,
  },
  permItem: {
    fontSize: 11,
    color: '#94A3B8',
    fontFamily: 'monospace',
  },
  googleConnectSubmitBtn: {
    backgroundColor: '#10B981',
    paddingVertical: 13,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  googleConnectSubmitText: {
    color: '#050507',
    fontSize: 11,
    fontWeight: '900',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  receiptHeaderBox: {
    backgroundColor: 'rgba(16, 185, 129, 0.10)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.30)',
    padding: Spacing.three,
    marginBottom: Spacing.three,
    alignItems: 'center',
  },
  receiptSourceText: {
    color: '#34D399',
    fontSize: 13,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  receiptSubtext: {
    color: '#CBD5E1',
    fontSize: 11,
    marginTop: 3,
  },
  receiptGrid: {
    gap: Spacing.two,
    marginBottom: Spacing.three,
  },
  receiptCardItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 12,
    padding: Spacing.three,
  },
  receiptIcon: {
    fontSize: 18,
    marginBottom: 4,
  },
  receiptCardLabel: {
    fontSize: 9,
    fontFamily: 'monospace',
    color: '#94A3B8',
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  receiptCardVal: {
    fontSize: 18,
    fontWeight: '900',
    color: '#FFFFFF',
    fontFamily: 'monospace',
    marginTop: 2,
  },
  receiptCardSub: {
    fontSize: 10,
    color: '#818CF8',
    fontFamily: 'monospace',
    marginTop: 2,
  },
  receiptConfirmBtn: {
    backgroundColor: '#34D399',
    paddingVertical: 13,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: Spacing.one,
  },
  receiptConfirmBtnText: {
    color: '#050507',
    fontSize: 11.5,
    fontWeight: '900',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  ghFormContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(52, 211, 153, 0.25)',
    padding: Spacing.three,
    gap: Spacing.three,
    marginBottom: Spacing.three,
  },
  ghFormGroup: {
    gap: 4,
  },
  ghInputLabel: {
    fontSize: 9.5,
    fontFamily: 'monospace',
    fontWeight: 'bold',
    color: '#34D399',
    letterSpacing: 0.8,
  },
  ghTextInput: {
    backgroundColor: 'rgba(5, 5, 7, 0.75)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: '#FFFFFF',
    fontSize: 13,
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  ghQuickChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 4,
  },
  ghQuickChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.10)',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  ghQuickChipActive: {
    backgroundColor: 'rgba(52, 211, 153, 0.20)',
    borderColor: '#34D399',
  },
  ghQuickChipText: {
    fontSize: 9,
    fontFamily: 'monospace',
    color: '#94A3B8',
  },
  ghQuickChipTextActive: {
    color: '#34D399',
    fontWeight: 'bold',
  },
  btnImportSensor: {
    backgroundColor: 'rgba(52, 211, 153, 0.15)',
    borderWidth: 1.5,
    borderColor: '#34D399',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  btnImportSensorText: {
    color: '#34D399',
    fontSize: 10.5,
    fontWeight: '900',
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
});
