import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Platform.OS === 'web' ? 20 : 16,
  },
  modalCard: {
    width: '100%',
    maxWidth: 500,
    maxHeight: '90%',
    backgroundColor: 'rgba(10, 14, 24, 0.98)',
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: 'rgba(212, 175, 55, 0.45)',
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(212, 175, 55, 0.15)',
    backgroundColor: 'rgba(18, 24, 38, 0.7)',
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerIcon: {
    fontSize: 24,
  },
  headerTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: '#FFE259',
    letterSpacing: 1.5,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  headerSubtitle: {
    fontSize: 10,
    color: '#94A3B8',
    marginTop: 1,
  },
  closeBtn: {
    padding: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  feedbackBannerBox: {
    backgroundColor: 'rgba(16, 185, 129, 0.18)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(16, 185, 129, 0.40)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  feedbackBannerText: {
    color: '#34D399',
    fontSize: 11,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    textAlign: 'center',
  },
  scrollBody: {
    padding: 20,
    gap: 16,
  },
  metricsBanner: {
    backgroundColor: 'rgba(212, 175, 55, 0.08)',
    borderWidth: 1.2,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    gap: 12,
  },
  mainStepsDisplay: {
    alignItems: 'center',
  },
  currentStepsNumber: {
    fontSize: 36,
    fontWeight: '900',
    color: '#FFFDE0',
    letterSpacing: 1,
    fontFamily: 'monospace',
    textShadowColor: 'rgba(255, 226, 89, 0.5)',
    textShadowRadius: 10,
  },
  stepsGoalLabel: {
    fontSize: 11,
    color: '#D4AF37',
    fontWeight: '700',
    letterSpacing: 1.1,
    fontFamily: 'monospace',
  },
  metricsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: '100%',
    borderTopWidth: 1,
    borderTopColor: 'rgba(212, 175, 55, 0.15)',
    paddingTop: 10,
  },
  metricItem: {
    alignItems: 'center',
  },
  metricLabel: {
    fontSize: 8.5,
    fontWeight: '900',
    color: '#94A3B8',
    letterSpacing: 1,
    fontFamily: 'monospace',
  },
  metricValue: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#FFF',
    marginTop: 2,
  },
  metricDivider: {
    width: 1,
    height: 20,
    backgroundColor: 'rgba(212, 175, 55, 0.2)',
  },
  sectionCard: {
    backgroundColor: 'rgba(15, 20, 32, 0.75)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 14,
    padding: 14,
    gap: 8,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '900',
    color: '#E2E8F0',
    letterSpacing: 1.2,
    fontFamily: 'monospace',
  },
  sectionDesc: {
    fontSize: 11,
    color: '#94A3B8',
    lineHeight: 16,
  },
  statusPill: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  statusPillActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    borderWidth: 1,
    borderColor: '#10B981',
  },
  statusPillInactive: {
    backgroundColor: 'rgba(148, 163, 184, 0.15)',
    borderWidth: 1,
    borderColor: '#64748B',
  },
  statusPillText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#FFF',
    fontFamily: 'monospace',
  },
  toggleSensorBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
    borderWidth: 1,
    borderColor: '#FFE259',
    borderRadius: 10,
    paddingVertical: 10,
    marginTop: 4,
  },
  toggleSensorBtnActive: {
    backgroundColor: '#FFE259',
  },
  toggleSensorBtnText: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#FFE259',
  },
  toggleSensorBtnTextActive: {
    color: '#050507',
  },
  inputRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  numericInput: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.3)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: '#FFF',
    fontSize: 14,
    fontFamily: 'monospace',
  },
  applyBtn: {
    backgroundColor: '#D4AF37',
    borderRadius: 10,
    paddingHorizontal: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  applyBtnText: {
    fontSize: 11.5,
    fontWeight: '900',
    color: '#050507',
    letterSpacing: 1,
  },
  chipsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  stepChip: {
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.35)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  stepChipText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#34D399',
    fontFamily: 'monospace',
  },
  stepChipNegative: {
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    borderColor: 'rgba(239, 68, 68, 0.35)',
  },
  stepChipTextNegative: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#F87171',
    fontFamily: 'monospace',
  },
  actionsFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 6,
  },
  goalEditorBox: {
    flex: 1,
    flexDirection: 'row',
    gap: 8,
  },
  secondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.25)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  secondaryBtnText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#FFE259',
  },
  resetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  resetBtnText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#EF4444',
  },
  sensitivityRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  sensBtn: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sensBtnActive: {
    backgroundColor: 'rgba(56, 189, 248, 0.16)',
    borderColor: '#38BDF8',
  },
  sensBtnTitle: {
    fontSize: 10.5,
    fontWeight: '900',
    color: '#94A3B8',
    fontFamily: 'monospace',
  },
  sensBtnTitleActive: {
    color: '#38BDF8',
  },
  sensBtnDesc: {
    fontSize: 8.5,
    color: '#64748B',
    marginTop: 2,
    textAlign: 'center',
  },
});
